version: "3"
services:

  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./server/static:/var/www/shop/static
      - ./server/media:/var/www/shop/media
    env_file:
      - .env
    depends_on:
      - app

  app:
    build: .
    container_name: django
    restart: always
    volumes:
      - ./server:/code/server
    env_file:
      - .env

  db:
    image: postgres:12-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: memcached:1.6.3-alpine
    container_name: memcached
    restart: always