version: "3"
services:
  nginx:
    image: nginx:1.17
    container_name: nginx_server
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: .
    container_name: app_server
    restart: always
    volumes:
      - ./server:/code/server

  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_PASSWORD: simple_password